### ISSUE TITLE
Installation of webgme-cli fails on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by sprinkjm** [webgme/webgme-cli#199] opened 2016-10-26 21:40 UTC
Brand new installation from disk on VMware.

```
sudo apt-get install git npm nodejs mongodb
git clone https://github.com/webgme/webgme
cd webgme
npm install
```
Fails: 

> > leveldown@1.5.0 install /home/webgme/webgme/node_modules/dynalite/node_modules/leveldown
> > prebuild --install
> 
> /usr/bin/env: node: No such file or directory
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm WARN optional dep failed, continuing leveldown@1.5.0
> 
> > webgme@2.6.0 postinstall /home/webgme/webgme
> > bower install && node ./utils/postinstall.js -c jsdoc_conf.json
> 
> /usr/bin/env: node: No such file or directory
> npm ERR! weird error 127
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! not ok code 0
> webgme@webgme:~/webgme$ node --version
> The program 'node' can be found in the following packages:
>  * node
>  * nodejs-legacy
> Try: sudo apt-get install <selected package>
> 

Install nodejs-legacy
```
sudo apt-get install nodejs-legacy
npm install
```
Success. Now webgme is installed, want to install webgme-cli

```
npm install webgme-cli
```
Fails:

> npm http 200 https://registry.npmjs.org/lodash
> npm http 304 https://registry.npmjs.org/npm
> npm http 304 https://registry.npmjs.org/plural
> npm http 304 https://registry.npmjs.org/commander
> npm http 304 https://registry.npmjs.org/ramda
> npm ERR! git fetch -a origin (git://github.com/brollb/commander.js) error: cannot open FETCH_HEAD: Permission denied
> npm ERR! Error: No compatible version found: commander@'brollb/commander.js'
> npm ERR! Valid install targets:
> npm ERR! ["0.0.1","0.0.3","0.0.4","0.0.5","0.1.0","0.2.0","0.2.1","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.5.0","0.5.1","0.6.0","0.6.1","0.5.2","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.1.0","1.1.1","1.2.0","1.3.0","1.3.1","1.3.2","2.0.0","2.1.0","2.2.0","2.3.0","2.4.0","2.5.0","2.5.1","2.6.0","2.7.0","2.7.1","2.8.0","2.8.1","2.9.0"]
> npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
> npm ERR!     at /usr/share/npm/lib/cache.js:638:10
> npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
> npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
> npm ERR!     at Object.oncomplete (fs.js:107:15)
> npm ERR! If you need help, you may report this log at:
> npm ERR!     <http://github.com/isaacs/npm/issues>
> npm ERR! or email it to:
> npm ERR!     <npm-@googlegroups.com>
> 
> npm ERR! System Linux 4.2.0-27-generic
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "webgme-cli"
> npm ERR! cwd /home/webgme/webgme
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/webgme/webgme/npm-debug.log
> npm ERR! not ok code 0
> webgme@webgme:~/webgme$ 
> 

Maybe sudo helps?

```
sudo npm install webgme-cli
```

> npm http GET https://registry.npmjs.org/longest
> npm http 304 https://registry.npmjs.org/longest
> 
> > webgme-cli@2.2.0 postinstall /home/webgme/webgme/node_modules/webgme-cli
> > node bin/install.js
> 
> 
> /home/webgme/webgme/node_modules/webgme-cli/bin/install.js:9
> spawnSync('node', [path.join(__dirname, 'build.js'), 'src', 'lib']);
> ^
> TypeError: undefined is not a function
>     at Object.<anonymous> (/home/webgme/webgme/node_modules/webgme-cli/bin/install.js:9:1)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! weird error 8
> npm ERR! not ok code 0
> webgme@webgme:~/webgme$ 
>

**Comment by pmeijer** [comment] 2016-10-26 22:18
There is no need to clone the webgme repo and the [webgme-cli tool](https://github.com/webgme/webgme-cli/blob/master/README.md#setting-up-a-webgme-app) should be installed [as a global npm module](https://docs.npmjs.com/getting-started/installing-npm-packages-globally).

Regarding your error it could be that you're behind a proxy that doesn't allow the git protocol, in that case you could try (suggested by an IT admin at NASA that had similar issues):

```
git config --global url.https://github.com/.insteadOf git://github.com/
```

In general avoid to use the sudo at npm installations (it will taint everything installed by that command).

**Comment by sprinkjm** [comment] 2016-10-26 23:25
It's not a proxy issue. I will post a new issue with the failure in trying to npm install inside the clone of webgme-cli

**Comment by brollb** [comment] 2016-10-26 23:57
It looks like the first issue failed because it could not find the `node` binary:
```
/usr/bin/env: node: No such file or directory
```

I believe the important part of the second failure is:
```
npm ERR! git fetch -a origin (git://github.com/brollb/commander.js) error: cannot open FETCH_HEAD: Permission denied
```
It looks like you needed sudo to install the npm package globally because of how nodejs is installed. I think this is relatively common when installing nodejs using package managers.

The third failure is caused by the fact that `nodejs-legacy` installs node v10 (given in the logs `npm ERR! node -v v0.10.25`) which is not officially supported by webgme/webgme-cli (the specific error is due to [spawnSync](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) not being available until v0.11.12 or higher - so it is throwing `TypeError: undefined is not a function`)

**All these problems should be fixed by installing node using [nvm](https://github.com/creationix/nvm) then using a supported version of nodejs (I personally usually use v6.x).** After installing nvm, you should be able to just run:
```
nvm install v6
```
This should install node v6.x and it should set it as your default in the terminal. If it isn't set to the default, you can fix that with `nvm alias default v6`.


Explanation:
Ubuntu installs nodejs as `nodejs` on the console (unlike any other distro/os I know of). This caused the first error. It installs nodejs system wide and stores the global npm packages in a location that needs root permissions to install to. This results in the second error. The last issue comes from the `nodejs-legacy` version being unsupported by webgme.

**Comment by sprinkjm** [comment] 2016-10-27 01:51
I am sorry to be such a n00b, but "installing node using nvm" is much more easily said than done. 

```
webgme@webgme:~/nvm$ sudo apt-get install nvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvm
webgme@webgme:~/nvm$ 
```

So I'll get the source and compile it (not my favorite to live on the bleeding edge, but ok):

```
webgme@webgme:~$ git clone https://github.com/creationix/nvm
Cloning into 'nvm'...
remote: Counting objects: 5525, done.
remote: Total 5525 (delta 0), reused 0 (delta 0), pack-reused 5525
Receiving objects: 100% (5525/5525), 1.59 MiB | 1003.00 KiB/s, done.
Resolving deltas: 100% (3350/3350), done.
Checking connectivity... done.
webgme@webgme:~$ cd nvm/
webgme@webgme:~/nvm$ npm install
npm http GET https://registry.npmjs.org/urchin
npm http GET https://registry.npmjs.org/replace
npm http GET https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/semver
npm http 200 https://registry.npmjs.org/replace
npm http GET https://registry.npmjs.org/replace/-/replace-0.3.0.tgz
npm http 200 https://registry.npmjs.org/urchin
npm http GET https://registry.npmjs.org/urchin/-/urchin-0.0.5.tgz
npm http 200 https://registry.npmjs.org/replace/-/replace-0.3.0.tgz
npm http 200 https://registry.npmjs.org/urchin/-/urchin-0.0.5.tgz
npm http GET https://registry.npmjs.org/nomnom
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/colors/-/colors-0.5.1.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm http 304 https://registry.npmjs.org/nomnom
npm http GET https://registry.npmjs.org/nomnom/-/nomnom-1.6.2.tgz
npm http 200 https://registry.npmjs.org/colors/-/colors-0.5.1.tgz
npm http 200 https://registry.npmjs.org/nomnom/-/nomnom-1.6.2.tgz
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
semver@5.3.0 node_modules/semver

urchin@0.0.5 node_modules/urchin

replace@0.3.0 node_modules/replace
├── colors@0.5.1
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
└── nomnom@1.6.2 (underscore@1.4.4)
webgme@webgme:~/nvm$ nvm
No command 'nvm' found, did you mean:
 Command 'kvm' from package 'qemu-kvm' (main)
 Command 'lvm' from package 'lvm2' (main)
 Command 'n-m' from package 'python-networkmanager' (universe)
 Command 'vm' from package 'mgetty-voice' (universe)
 Command 'nm' from package 'binutils' (main)
 Command 'nm' from package 'binutils-multiarch' (main)
 Command 'pvm' from package 'pvm' (universe)
 Command 'npm' from package 'npm' (universe)
 Command 'nvi' from package 'nvi' (universe)
 Command 'nam' from package 'nam' (universe)
nvm: command not found
webgme@webgme:~/nvm$
```

My Spidey-Senses tell me I will have the same problem I saw before:
```
webgme@webgme:~/nvm$ npm install -g nvm
npm http GET https://registry.npmjs.org/nvm
npm http 200 https://registry.npmjs.org/nvm
npm WARN deprecated nvm@0.0.4: This is NOT the correct nvm. Visit http://nvm.sh and use the curl command to install it.
npm http GET https://registry.npmjs.org/nvm/-/nvm-0.0.4.tgz
npm http 200 https://registry.npmjs.org/nvm/-/nvm-0.0.4.tgz
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/nvm'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/nvm']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/nvm',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/nvm',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nvm"
npm ERR! cwd /home/webgme/nvm
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/nvm
npm ERR! fstream_path /usr/local/lib/node_modules/nvm
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/nvm'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/webgme/nvm/npm-debug.log
npm ERR! not ok code 0
webgme@webgme:~/nvm$
```

**Comment by brollb** [comment] 2016-10-27 02:15
No worries. You should be able to install it with 
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
```
Then close and re-open the terminal and check if the `nvm` command exists. If not, you probably want to add the following to your `~/.zshrc`, `~/.bashrc`, `~/.bash_profile`, etc:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
```

Then re-open the terminal and try again

**Comment by sprinkjm** [comment] 2016-10-27 18:03
Success! Because I tainted with the standard approach when install fails (insert sudo make me a sandwich joke later), I had to do the following (presented in order)

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
```
close, then reopen your terminal. Now:
```
nvm install v6
```
Takes some time, then success!

next:
```
git clone https://github.com/webgme/webgme-cli
cd webgme-cli
npm install webgme-cli -g
```
Fails, with lots of errors in permissions. 

> webgme@webgme:~/webgme-cli$ npm install webgme-cli -g
> npm ERR! Linux 4.2.0-27-generic
> npm ERR! argv "/home/webgme/.nvm/versions/node/v6.9.1/bin/node" "/home/webgme/.nvm/versions/node/v6.9.1/bin/npm" "install" "webgme-cli" "-g"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! path /home/webgme/.npm/_git-remotes/_templates
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall mkdir
> 
> npm ERR! Error: EACCES: permission denied, mkdir '/home/webgme/.npm/_git-remotes/_templates'
> npm ERR!     at Error (native)
> npm ERR!  { Error: EACCES: permission denied, mkdir '/home/webgme/.npm/_git-remotes/_templates'
> npm ERR!     at Error (native)
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'mkdir',
> npm ERR!   path: '/home/webgme/.npm/_git-remotes/_templates',
> npm ERR!   parent: 'webgme-cli' }
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/webgme/webgme-cli/npm-debug.log
> webgme@webgme:~/webgme-cli$

Probably we tainted our install by trying to run sudo to install via npm before, so:
```
cd ~
rm -rf ~/.npm ~/.config/configstore
```
Fails because we are not permitted to remove these files. So we need to sudo. Be careful with -rf with sudo:
```
sudo rm -rf ~/.npm ~/.config/configstore
```
Now, back to installing webgme-cli
```
cd ~/webgme-cli
npm install webgme-cli
```
We want to have it available from bash, so
```
npm install webgme-cli -g
```
Look for a line above that says "Note: Autocomplete for bash can be enabled with:"

Then execute that line (mine is below, but won't match yours unless your username is webgme) and source your .bashrc file
```
echo ". /home/webgme/.nvm/versions/node/v6.9.1/lib/node_modules/webgme-cli/extra/webgme.completion.bash" >> ~/.bashrc
source ~/.bashrc
```

Yay!

**Comment by brollb** [comment] 2016-10-28 22:08
One minor thing - `npm install webgme-cli -g` will retrieve webgme-cli from npm's repos so there is no need to clone it :)

Good to hear it is up and going! Let me know if you have any other issues/comments/etc!

**Closed by brollb** 2016-10-28 22:08 UTC

**Comment by brollb** [comment] 2016-11-16 18:06
If anyone else stumbles upon this issue, the tl;dr version is:

> **All these problems should be fixed by installing node using [nvm](https://github.com/creationix/nvm) then using a supported version of nodejs (I personally usually use v6.x).** After installing nvm, you should be able to just run:
```
nvm install v6
```
This should install node v6.x and it should set it as your default in the terminal. If it isn't set to the default, you can fix that with `nvm alias default v6`.

Feel free to read through for the fine points and details but using nvm should avoid issues w/ having to use `sudo`, incorrect nodejs versions, and unconventional binary naming (like in ubuntu).
